### ISSUE TITLE
Add css code without conversion

### ISSUE THREAD

**Issue by vkhv** [justim/postcss-svg-fallback#7]
Hi, i want use your plugin :) but I need to just add fallback in the css code, I have no need of conversion. Is it possible?  :) And i don't need to specify the size.

What I need:

``` css
.icon {
    background: url(images/sun-is-shining.svg) no-repeat;
}
```

to:

``` css
.no-svg .icon {
    background-image: url(images/sun-is-shining.png);
}
```

Many thanks for considering my request!
